# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-01 04:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_empleado', models.CharField(max_length=10)),
                ('fecha_ingreso', models.DateTimeField()),
                ('puesto', models.CharField(max_length=40)),
                ('adscripcion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogos.Adscripcion')),
                ('clave_plaza', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogos.Plaza')),
                ('datos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogos.Persona')),
            ],
        ),
    ]
